### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by iamimsh** [Engati/Engati_SDK_iOS#1]
I just updated my Xcode to Version 11.4 (11E146) and I started getting this error for Engati.

`Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler`

I tried to clean build folder and then run again, removed pods and installed again... does't work still...

I think you have to upload a new version built by Xcode 11.4.

**Comment by Engati** [comment]
Thank you for reporting.
Support for XCode 11.4 has been provided in version 1.8.0.
Please do "pod update".

Regards,
Engati Team
